name: Add labelled PRs to project

on:
  pull_request:
    types: [ labeled ]

jobs:
  add-to-project:
    if: ${{ github.event.label.name == 'dependencies' }}
    name: Add to main project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/adapt-security/projects/5
          github-token: ${{ secrets.PROJECTS_SECRET }}
