name: Add to main project
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    uses: adapt-security/.github/.github/workflows/new.yml@main
    secrets:
      PROJECTS_SECRET: ${{ secrets.ADD_TO_PROJECT_PAT }}
