name: Add to project
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened
jobs:
  add-to-project:
    uses: adapt-security/.github/.github/workflows/new.yml@main
    secrets:
      PROJECTS_SECRET: ${{ secrets.ADD_TO_PROJECT_PAT }}
